// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBO6PuwyDaSh7fnIBPuMHhUTE9RJOHYU-4',
    appId: '1:324928567555:web:8d03b729027b38df751136',
    messagingSenderId: '324928567555',
    projectId: 'astrotwins-fc3a0',
    authDomain: 'astrotwins-fc3a0.firebaseapp.com',
    storageBucket: 'astrotwins-fc3a0.appspot.com',
    measurementId: 'G-0RT3TGVN18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPljrh0-0saYidlTJq3kwhTvr0oPQrLIw',
    appId: '1:324928567555:android:e6242da1fa0b8f47751136',
    messagingSenderId: '324928567555',
    projectId: 'astrotwins-fc3a0',
    storageBucket: 'astrotwins-fc3a0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCK_PY1Y3iLHar_BaQCf6ezArZ-5zLSAVA',
    appId: '1:324928567555:ios:75879276bdc72c72751136',
    messagingSenderId: '324928567555',
    projectId: 'astrotwins-fc3a0',
    storageBucket: 'astrotwins-fc3a0.appspot.com',
    androidClientId: '324928567555-0t23mc1603kgnk6qfbmiu4do65ba2o2a.apps.googleusercontent.com',
    iosClientId: '324928567555-qfpr95g8g768uaf0ustsv89vtiu7ds5o.apps.googleusercontent.com',
    iosBundleId: 'com.myastrotwins.astroTwins',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCK_PY1Y3iLHar_BaQCf6ezArZ-5zLSAVA',
    appId: '1:324928567555:ios:75879276bdc72c72751136',
    messagingSenderId: '324928567555',
    projectId: 'astrotwins-fc3a0',
    storageBucket: 'astrotwins-fc3a0.appspot.com',
    androidClientId: '324928567555-0t23mc1603kgnk6qfbmiu4do65ba2o2a.apps.googleusercontent.com',
    iosClientId: '324928567555-qfpr95g8g768uaf0ustsv89vtiu7ds5o.apps.googleusercontent.com',
    iosBundleId: 'com.myastrotwins.astroTwins',
  );
}
